spring:
  web:
    resources:
      static-locations: file:./static/
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/radindb
    username: postgres
    password: radin
    driverClassName: org.postgresql.Driver

  application:
    name: test

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.cloud.gateway: DEBUG



